# site settings

title: Ethan Hsu
description: Ethan Hsu online resume
baseurl: ""
repo: https://github.com/EtHsu0/EtHsu0.github.io

# author settings

author:
  name: Ethan Hsu
  # email: username@domain.com
# photo: /assets/background.jpeg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
